import { v4 } from "uuid";

export const googleCategories = [
  { id: v4(), category: "Dispositivos y accesorios" },
  { id: v4(), category: "Accesorios" },
  { id: v4(), category: "Aplicaciones y juegos" },
  { id: v4(), category: "Artes, manualidades y costura" },
  { id: v4(), category: "Libros audibles y originales" },
  { id: v4(), category: "Automotor" },
  { id: v4(), category: "Bebé" },
  { id: v4(), category: "Belleza y cuidado Personal" },
  { id: v4(), category: "Libros" },
  { id: v4(), category: "Productos para cámaras y fotografías" },
  { id: v4(), category: "CD y vinilo" },
  { id: v4(), category: "Teléfonos móviles y accesorios" },
  { id: v4(), category: "Compromiso climático amigable" },
  { id: v4(), category: "Ropa, zapatos y joyería" },
  { id: v4(), category: "Monedas coleccionables" },
  { id: v4(), category: "Computadoras y accesorios" },
  { id: v4(), category: "Recursos educativos digitales" },
  { id: v4(), category: "Música Digital" },
  { id: v4(), category: "Electrónica" },
  { id: v4(), category: "Coleccionables de entretenimiento" },
  { id: v4(), category: "Tarjetas de regalo" },
  { id: v4(), category: "Abarrotes y comida gourmet" },
  { id: v4(), category: "Productos hechos a mano" },
  { id: v4(), category: "Salud y hogar" },
  { id: v4(), category: "Hogar y cocina" },
  { id: v4(), category: "Industrial y científico" },
  { id: v4(), category: "Tienda Kindle" },
  { id: v4(), category: "Cocina y comedor" },
  { id: v4(), category: "Películas y televisión" },
  { id: v4(), category: "Instrumentos musicales" },
  { id: v4(), category: "Productos de oficina" },
  { id: v4(), category: "Patio, césped y jardín" },
  { id: v4(), category: "Suministros de mascotas" },
  { id: v4(), category: "Software" },
  { id: v4(), category: "Deportes y aire libre" },
  { id: v4(), category: "Coleccionables deportivos" },
  { id: v4(), category: "Herramientas y mejoras del hogar" },
  { id: v4(), category: "Juguetes y Juegos" },
  { id: v4(), category: "Hallazgos únicos" },
  { id: v4(), category: "Juegos de vídeo" },
];
