export const googleCategories = [
  {
    id: 1,
    category: "Artículos para animales y mascotas",
  },
  {
    id: 3237,
    category: "Animales y Artículos para Mascotas > Animales Vivos",
  },
  {
    id: 2,
    category: "Animales y Artículos para Mascotas > Artículos para mascotas",
  },
  {
    id: 166,
    category: "Ropa y Accesorios",
  },
  {
    id: 1604,
    category: "Ropa y Accesorios > Ropa",
  },
  {
    id: 167,
    category: "Ropa y Accesorios > Accesorios de Vestir",
  },
  {
    id: 184,
    category: "Ropa y Accesorios > Disfraces y Accesorios",
  },
  {
    id: 6552,
    category: "Ropa y Accesorios > Accesorios para Bolsos y Carteras",
  },
  {
    id: 6551,
    category: "Ropa y Accesorios > Bolsos, Carteras y Estuches",
  },
  {
    id: 188,
    category: "Ropa y Accesorios > Joyería",
  },
  {
    id: 1933,
    category: "Ropa y accesorios > Accesorios para calzado",
  },
  {
    id: 187,
    category: "Ropa y Accesorios > Zapatos",
  },
  {
    id: 8,
    category: "Arte y entretenimiento",
  },
  {
    id: 499969,
    category: "Arte y entretenimiento > Entradas para eventos",
  },
  {
    id: 5710,
    category: "Arte y entretenimiento > Aficiones y artes creativas",
  },
  {
    id: 5709,
    category: "Arte y Entretenimiento > Fiesta y Celebración",
  },
  {
    id: 537,
    category: "Bebé y niño pequeño",
  },
  {
    id: 4678,
    category: "Bebés y Niños Pequeños > Bañadores para Bebés",
  },
  {
    id: 5859,
    category: "Bebés y Niños Pequeños > Sets de Regalo para Bebés",
  },
  {
    id: 5252,
    category: "Bebés y Niños Pequeños > Salud del Bebé",
  },
  {
    id: 540,
    category: "Bebés y niños pequeños > Seguridad del bebé",
  },
  {
    id: 2847,
    category:
      "Bebés y niños pequeños > Juguetes y equipos de actividades para bebés",
  },
  {
    id: 2764,
    category: "Bebés y Niños Pequeños > Transporte Bebés",
  },
  {
    id: 4386,
    category: "Bebés y Niños Pequeños > Accesorios Transporte Bebé",
  },
  {
    id: 548,
    category: "Bebés y niños pequeños > Cambio de pañales",
  },
  { id: 561, category: "Bebés y niños pequeños > Enfermería y alimentación" },
  {
    id: 6952,
    category: "Bebés y niños pequeños > Entrenamiento para ir al baño",
  },
  {
    id: 6899,
    category: "Bebés y Niños Pequeños > Mantas Para Envolver y Recibir",
  },
  { id: 111, category: "Negocios e Industria" },
  { id: 5863, category: "Empresas e Industria > Publicidad y Marketing" },
  { id: 112, category: "Empresas e Industria > Agricultura" },
  {
    id: 7261,
    category: "Empresas e Industria > Componentes de control de automatización",
  },
  { id: 114, category: "Empresas e Industria > Construcción" },
  { id: 7497, category: "Empresas e Industrias > Odontología" },
  { id: 2155, category: "Empresas e Industria > Cine y Televisión" },
  { id: 1813, category: "Negocios e Industria > Finanzas y Seguros" },
  { id: 135, category: "Negocios e Industria > Servicio de Alimentos" },
  {
    id: 1827,
    category: "Negocios e Industria > Silvicultura y explotación maderera",
  },
  { id: 7240, category: "Empresas e Industriales > Peluquería y Cosmetología" },
  { id: 1795, category: "Negocios e Industria > Maquinaria Pesada" },
  { id: 1475, category: "Negocios e Industria > Hotelería y Hospitalidad" },
  { id: 5830, category: "Empresas e Industria > Almacenamiento Industrial" },
  {
    id: 8025,
    category: "Empresas e Industria > Accesorios de Almacenamiento Industrial",
  },
  {
    id: 500086,
    category: "Negocios e Industria > Carros y carritos de limpieza",
  },
  { id: 1556, category: "Negocios e Industria > Aplicación de la ley" },
  { id: 1470, category: "Negocios e Industria > Manufactura" },
  { id: 6987, category: "Negocios e Industria > Manipulación de Materiales" },
  { id: 2496, category: "Empresas e Industria > Médico" },
  { id: 2187, category: "Negocios e Industria > Minería y Canteras" },
  { id: 4285, category: "Empresas e Industria > Perforaciones y Tatuajes" },
  { id: 138, category: "Negocios e Industria > Comercio minorista" },
  { id: 1624, category: "Negocios e Industria > Ciencia y Laboratorio" },
  { id: 976, category: "Empresas e Industria > Señalización" },
  {
    id: 2047,
    category:
      "Empresas e Industria > Equipo de protección de seguridad laboral",
  },
  { id: 141, category: "Cámaras y Ópticas" },
  {
    id: 2096,
    category: "Cámaras y Óptica > Accesorios para Cámaras y Ópticas",
  },
  { id: 142, category: "Cámaras y Óptica > Cámaras" },
  { id: 156, category: "Cámaras y Óptica > Óptica" },
  { id: 39, category: "Cámaras y Ópticas > Fotografía" },
  { id: 222, category: "Electrónica" },
  { id: 3356, category: "Electrónica > Equipos Arcade" },
  { id: 223, category: "Electrónica > Audio" },
  { id: 3702, category: "Electrónica > Placas de Circuito y Componentes" },
  { id: 262, category: "Electrónica > Comunicaciones" },
  { id: 1801, category: "Electrónica > Componentes" },
  { id: 278, category: "Electrónica > Computadoras" },
  { id: 2082, category: "Electrónica > Accesorios Electrónicos" },
  { id: 3895, category: "Electrónica > Accesorios GPS" },
  { id: 339, category: "Electrónica > Sistemas de Navegación GPS" },
  { id: 6544, category: "Electrónica > Dispositivos de Rastreo GPS" },
  { id: 340, category: "Electrónica > Electrónica Marina" },
  { id: 342, category: "Electrónica > Redes" },
  {
    id: 345,
    category: "Electrónica > Imprimir, Copiar, Escanear y Enviar Fax",
  },
  { id: 912, category: "Electrónica > Detectores de Radar" },
  { id: 500091, category: "Electrónica > Radares de Velocidad" },
  { id: 4488, category: "Electrónica > Dispositivos de Cobro de Peaje" },
  { id: 386, category: "Electrónica > Vídeo" },
  {
    id: 1270,
    category: "Electrónica > Accesorios para Consolas de Videojuegos",
  },
  { id: 1294, category: "Electrónica > Consolas de Videojuegos" },
  { id: 412, category: "Alimentos, Bebidas y Tabaco" },
  { id: 413, category: "Alimentos, Bebidas y Tabaco > Bebidas" },
  { id: 422, category: "Alimentos, Bebidas y Tabaco > Artículos Alimenticios" },
  { id: 435, category: "Alimentos, Bebidas y Tabaco > Productos de Tabaco" },
  { id: 436, category: "Muebles" },
  { id: 554, category: "Muebles > Muebles para bebés y niños pequeños" },
  { id: 6433, category: "Muebles > Camas y Complementos" },
  { id: 441, category: "Muebles > Bancos" },
  { id: 6356, category: "Muebles > Armarios y Almacenaje" },
  { id: 442, category: "Mobiliario > Carritos e Islas" },
  { id: 7248, category: "Muebles > Accesorios para Sillas" },
  { id: 443, category: "Mobiliario > Sillas" },
  {
    id: 457,
    category: "Muebles > Centros de entretenimiento y soportes para TV",
  },
  { id: 6345, category: "Muebles > Conjuntos de Muebles" },
  { id: 6860, category: "Muebles > Estructuras de Futón" },
  { id: 2786, category: "Muebles > Almohadillas para Futón" },
  { id: 450, category: "Muebles > Futones" },
  { id: 6362, category: "Mobiliario > Mobiliario de Oficina" },
  { id: 503765, category: "Mobiliario > Accesorios Mobiliario Oficina" },
  { id: 458, category: "Muebles > Otomanos" },
  { id: 4299, category: "Mobiliario > Mobiliario Exterior" },
  { id: 6963, category: "Muebles > Accesorios para muebles de exterior" },
  { id: 6915, category: "Muebles > Accesorios Separadores de Ambientes" },
  { id: 4163, category: "Muebles > Separadores de ambientes" },
  { id: 464, category: "Muebles > Estanterías" },
  { id: 8023, category: "Muebles > Accesorios Estanterías" },
  { id: 7212, category: "Muebles > Accesorios para Sofás" },
  { id: 460, category: "Mobiliario > Sofás" },
  { id: 6913, category: "Muebles > Accesorios para Mesa" },
  { id: 6392, category: "Muebles > Mesas" },
  { id: 632, category: "Ferretería" },
  { id: 503739, category: "Ferretería > Consumibles de Construcción" },
  { id: 115, category: "Ferretería > Materiales de Construcción" },
  { id: 128, category: "Ferretería > Cercas y Barreras" },
  { id: 543575, category: "Ferretería > Combustible" },
  {
    id: 502975,
    category: "Ferretería > Contenedores y Tanques de Combustible",
  },
  { id: 2878, category: "Ferretería > Accesorios Ferretería" },
  { id: 500096, category: "Ferretería > Ferretería Bombas" },
  {
    id: 499873,
    category: "Ferretería > Calefacción, Ventilación y Aire Acondicionado",
  },
  { id: 1974, category: "Ferretería > Cerraduras y llaves" },
  { id: 133, category: "Ferretería > Fontanería" },
  { id: 127, category: "Hardware > Energía y Suministros Eléctricos" },
  { id: 499982, category: "Ferretería > Motores Pequeños" },
  { id: 1910, category: "Ferretería > Tanques de Almacenamiento" },
  { id: 3650, category: "Ferretería > Accesorios para herramientas" },
  { id: 1167, category: "Ferretería > Herramientas" },
  { id: 469, category: "Salud y Belleza" },
  { id: 491, category: "Salud y Belleza > Cuidado de la Salud" },
  { id: 5573, category: "Salud y Belleza > Limpieza y Cuidado de Joyas" },
  { id: 2915, category: "Salud y Belleza > Cuidado Personal" },
  { id: 536, category: "Hogar y Jardín" },
  { id: 574, category: "Casa y Jardín > Accesorios de Baño" },
  { id: 359, category: "Hogar y Jardín > Seguridad para el Hogar y Negocios" },
  { id: 696, category: "Casa y Jardín > Decoración" },
  { id: 5835, category: "Casa y Jardín > Preparación para Emergencias" },
  {
    id: 2862,
    category: "Casa y Jardín > Accesorios Chimeneas y Estufas de Leña",
  },
  { id: 6792, category: "Casa y Jardín > Chimeneas" },
  {
    id: 1679,
    category:
      "Hogar y jardín > Seguridad contra inundaciones, incendios y gases",
  },
  { id: 3348, category: "Casa y Jardín > Accesorios para Electrodomésticos" },
  { id: 604, category: "Casa y Jardín > Electrodomésticos" },
  { id: 630, category: "Casa y Jardín > Artículos para el Hogar" },
  { id: 638, category: "Casa y Jardín > Cocina y Comedor" },
  { id: 689, category: "Hogar y jardín > Césped y jardín" },
  { id: 594, category: "Casa y Jardín > Iluminación" },
  { id: 2956, category: "Casa y Jardín > Accesorios de Iluminación" },
  { id: 4171, category: "Casa y Jardín > Ropa de Cama y Ropa de Cama" },
  { id: 4358, category: "Casa y Jardín > Sombrillas y Paraguas de Lluvia" },
  { id: 985, category: "Casa y Jardín > Plantas" },
  { id: 729, category: "Hogar y Jardín > Piscina y Spa" },
  { id: 600, category: "Casa y Jardín > Accesorios para fumadores" },
  { id: 6173, category: "Casa y Jardín > Fundas y Fundas Paraguas" },
  { id: 2639, category: "Casa y Jardín > Estufas de Leña" },
  { id: 5181, category: "Maletas y Bolsos" },
  { id: 100, category: "Maletas y Bolsos > Mochilas" },
  { id: 101, category: "Maletas y Bolsos > Maletines" },
  { id: 108, category: "Maletas y Bolsos > Neceseres y Cosméticos" },
  { id: 549, category: "Maletas y Bolsos > Bolsas para Pañales" },
  { id: 502974, category: "Maletas y Bolsos > Cajas Secas" },
  { id: 103, category: "Maletas y Bolsos > Bolsas de Lona" },
  { id: 104, category: "Maletas y Bolsos > Riñoneras" },
  { id: 105, category: "Maletas y Bolsos > Portatrajes" },
  { id: 110, category: "Maletas y Bolsos > Accesorios para Equipaje" },
  { id: 106, category: "Maletas y Bolsos > Bolsas Messenger" },
  { id: 5608, category: "Maletas y Bolsos > Totes de Compra" },
  { id: 107, category: "Maletas y Bolsos > Maletas" },
  { id: 6553, category: "Maletas y Bolsos > Maletas de Tren" },
  { id: 772, category: "Madura" },
  { id: 773, category: "Madura > Erótica" },
  { id: 780, category: "Maduro > Armas" },
  { id: 783, category: "Medios" },
  { id: 784, category: "Medios > Libros" },
  {
    id: 499995,
    category: "Medios > Planos de proyectos de carpintería y ebanistería",
  },
  { id: 839, category: "Medios > DVD y vídeos" },
  { id: 886, category: "Medios > Revistas y Periódicos" },
  { id: 855, category: "Medios > Música y Grabaciones de Sonido" },
  { id: 5037, category: "Medios > Manuales de productos" },
  { id: 887, category: "Medios > Partituras" },
  { id: 922, category: "Artículos de Oficina" },
  { id: 6174, category: "Material Oficina > Accesorios Libros" },
  {
    id: 8078,
    category: "Artículos de Oficina > Almohadillas y Secantes de Escritorio",
  },
  { id: 923, category: "Material de Oficina > Archivado y Organización" },
  {
    id: 932,
    category: "Artículos de Oficina > Artículos de Oficina en General",
  },
  { id: 5829, category: "Artículos para Oficina > Selladores de Impulso" },
  { id: 8499, category: "Artículos para Oficina > Escritorios Portátiles" },
  { id: 2435, category: "Artículos para Oficina > Placas de Nombres" },
  {
    id: 6519,
    category: "Artículos para Oficina > Tapetes para Oficina y Sillas",
  },
  { id: 6373, category: "Artículos para Oficina > Carritos para Oficina" },
  { id: 950, category: "Artículos de Oficina > Equipos de Oficina" },
  { id: 2986, category: "Artículos de Oficina > Instrumentos de Oficina" },
  { id: 2014, category: "Material de oficina > Manipulación de papel" },
  { id: 964, category: "Material de Oficina > Material de Presentación" },
  { id: 2636, category: "Artículos de Oficina > Artículos de Envío" },
  { id: 5605, category: "Religiosos y Ceremoniales" },
  {
    id: 5606,
    category:
      "Religiosos y Ceremoniales > Suministros para Ceremonias Conmemorativas",
  },
  { id: 97, category: "Religiosos y Ceremoniales > Artículos Religiosos" },
  {
    id: 5455,
    category: "Religiosos y Ceremoniales > Suministros para Ceremonias de Boda",
  },
  { id: 2092, category: "Software" },
  { id: 313, category: "Software > Software informático" },
  { id: 5032, category: "Software > Bienes Digitales y Moneda" },
  { id: 1279, category: "Software > Software de Videojuegos" },
  { id: 988, category: "Artículos deportivos" },
  { id: 499713, category: "Artículos Deportivos > Atletismo" },
  { id: 990, category: "Artículos deportivos > Ejercicio y fitness" },
  { id: 1001, category: "Artículos Deportivos > Juegos de Interior" },
  { id: 1011, category: "Artículos deportivos > Recreación al aire libre" },
  { id: 1239, category: "Juguetes y Juegos" },
  { id: 4648, category: "Juguetes y Juegos > Temporizadores de Juegos" },
  { id: 3793, category: "Juguetes y Juegos > Juegos" },
  { id: 1249, category: "Juguetes y Juegos > Equipos de Juego al Aire Libre" },
  { id: 3867, category: "Juguetes y Juegos > Rompecabezas" },
  { id: 1253, category: "Juguetes y Juegos > Juguetes" },
  { id: 888, category: "Vehículos y repuestos" },
  {
    id: 5613,
    category: "Vehículos y Repuestos > Repuestos y Accesorios para Vehículos",
  },
  { id: 5614, category: "Vehículos y Piezas > Vehículos" },
];
